// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for ROS 2 Nervous System documentation
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: ROS 2 Nervous System',
      items: [
        {
          type: 'category',
          label: 'Introduction to ROS 2',
          items: [
            'module1/intro-to-ros2',
            'module1/intro-to-ros2-exercise',
            'module1/intro-to-ros2-quiz',
          ],
        },
        {
          type: 'category',
          label: 'ROS 2 Communication & Python AI',
          items: [
            'module1/ros2-communication-python-ai',
            'module1/ros2-communication-python-ai-exercise',
            'module1/ros2-communication-python-ai-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Humanoid Structure with URDF',
          items: [
            'module1/humanoid-structure-urdf',
            'module1/humanoid-structure-urdf-exercise',
            'module1/humanoid-structure-urdf-quiz',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'category',
          label: 'Physics Simulation with Gazebo',
          items: [
            'module2/gazebo-physics-simulation',
            'module2/gazebo-physics-simulation-exercise',
            'module2/gazebo-physics-simulation-quiz',
          ],
        },
        {
          type: 'category',
          label: 'High-Fidelity Environments with Unity',
          items: [
            'module2/unity-high-fidelity-rendering',
            'module2/unity-high-fidelity-rendering-exercise',
            'module2/unity-high-fidelity-rendering-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Simulated Sensors (LiDAR, Depth, IMU)',
          items: [
            'module2/simulated-sensors',
            'module2/simulated-sensors-exercise',
            'module2/simulated-sensors-quiz',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module3/intro-to-isaac',
        {
          type: 'category',
          label: 'Isaac Sim for Photorealistic Simulation',
          items: [
            'module3/isaac-sim-photorealistic-simulation',
            'module3/isaac-sim-photorealistic-simulation-exercise',
            'module3/isaac-sim-photorealistic-simulation-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Isaac ROS for Accelerated Perception',
          items: [
            'module3/isaac-ros-accelerated-perception',
            'module3/isaac-ros-accelerated-perception-exercise',
            'module3/isaac-ros-accelerated-perception-quiz',
          ],
        },
        {
          type: 'category',
          label: 'Nav2 for Humanoid Path Planning',
          items: [
            'module3/nav2-path-planning-humanoids',
            'module3/nav2-path-planning-humanoids-exercise',
            'module3/nav2-path-planning-humanoids-quiz',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
